export const alphabet = {

    empty: `No alphabets found. Click on "<strong>New Alphabet</strong>" to create new one!`,

    head: {

        title: "Alphabet",
        subtitle: "Alphabets are used to generate passwords.",

        button: {
            create: "New alphabet"
        },

    },

    button: {
        update: {
            name: "Update Alphabet"
        },
        delete: {
            name: "Remove Alphabet"
        }
    },

    form: {
        create: {
            name: {
                label: "Name",
                placeholder: "Display Name"
            },
            identifier: {
                label: "Identifier",
                placeholder: "e.g. alphabet-1",
                helper: "This is used to generate the password."
            },
            characters: {
                label: "Alphabet",
                placeholder: "Characters (e.g. abcdef...)",
                helper: "This is used to generate the password."
            },
            description: {
                label: "Description",
                placeholder: "Description"
            },
            submit: "Create alphabet"
        },
        update: {
            name: {
                label: "Name",
                placeholder: "Display Name"
            },
            identifier: {
                label: "Identifier",
                placeholder: "e.g. alphabet-1",
                helper: "This is used to generate the password."
            },
            characters: {
                label: "Alphabet",
                placeholder: "Characters (e.g. abcdef...)",
                helper: "This is used to generate the password."
            },
            description: {
                label: "Description",
                placeholder: "Description"
            },
            submit: "Update alphabet"
        },
    },

    modal: {

        info: {
            title: "¿How it works?",
            body: `
                <p>
                    These alphabets are used when creating passwords. From here, you can delete, modify or create new alphabets that suit your needs.
                </p>
                <p>
                    You must be careful when modifying an alphabet because if you have generated a password with an alphabet and then modify it, the password will also be modified.
                </p>
                <p>
                    Passwords are generated by creating a hash including the alphabet identifier, in addition to using the characters of the alphabet in the length and order they are in. Therefore, modifying an alphabet would completely change the generated passwords.
                </p>
            `
        },

        create: {
            title: "Create Alphabet"
        },

        update: {
            title: "Update Alphabet"
        },

        delete: {
            title: "Delete Alphabet",
            body: `You're sure? Your passwords that use "<strong>{{name}}</strong>" alphabet <strong>will be broken</strong> and cannot be displayed.`,
            submit: "Yes, delete alphabet!",
            cancel: "Cancel"
        }

    }

}